### ISSUE TITLE
Errors with theme

### ISSUE THREAD

**Issue by Giulianoberaldo** [vojtasvoboda/oc-newage-theme#3]
hello. i like and use your theme, but i have found a little error: after that i click on the anchor, the others don' t work, so i can' t move from #download, to #contact. Another problem that i have is that on phone it appear a MENU icon, but there aren' tany links inside. How to add it here? thanks you

**Comment by vojtasvoboda** [comment]
Hello @Giulianoberaldo, I just tried fresh installation of OctoberCMS with this theme and everything works OK. Please, try this demo: https://blackrockdigital.github.io/startbootstrap-new-age/ Do you have same problems on demo?

**Comment by Giulianoberaldo** [comment]
yes, with this demo there 'are no problems..
maybe the server is low quality... it is free hosting...
Thanks you

Il giorno ven 22 mar 2019 alle ore 21:35 Vojta Svoboda <
notifications@github.com> ha scritto:

**Comment by Giulianoberaldo** [comment]
i have install again in localhost on my NAS synology, but it have the same
problem with theme.
what is wrong?
Thanks you

Il giorno ven 22 mar 2019 alle ore 22:31 Beraldo Giuliano <tclone0@gmail.com>
ha scritto:

**Comment by vojtasvoboda** [comment]
Please check Chrome developer console for some errors. Which browser do you use? Try to clear cache by `php artisan cache:clear` or `php artisan view:clear` command.

**Comment by Giulianoberaldo** [comment]
i use chrome.
i have cancel cache with a plugin for october, but nothing.


Il giorno sab 23 mar 2019 alle ore 15:17 Vojta Svoboda <
notifications@github.com> ha scritto:

**Comment by vojtasvoboda** [comment]
And how about Chrome console? Any errors, warnings?

**Comment by Giulianoberaldo** [comment]
I can't use chrome console..
If i make a fresh install you can check it?
Need admin credentials and server too?

Il dom 24 mar 2019, 13:15 Vojta Svoboda <notifications@github.com> ha
scritto:

**Comment by vojtasvoboda** [comment]
Just put it somewhere online and send me a link.

**Comment by Giulianoberaldo** [comment]
https://worldcapitals.tk
just a moment, installation is running

Il giorno dom 24 mar 2019 alle ore 13:32 Vojta Svoboda <
notifications@github.com> ha scritto:

**Comment by Giulianoberaldo** [comment]
this should be the console..
it work in localhost
... no more online...
i'm trying again.....

Il giorno dom 24 mar 2019 alle ore 14:49 Beraldo Giuliano <tclone0@gmail.com>
ha scritto:

**Comment by Giulianoberaldo** [comment]
this is in my localhost:

woodcreations.tk/install
tell me if it work or not...

Thanks you



Il giorno dom 24 mar 2019 alle ore 15:19 Beraldo Giuliano <tclone0@gmail.com>
ha scritto:

**Comment by Giulianoberaldo** [comment]
I HAVE FOUND THE PROBLEM!!
ITSN' T THE SERVER, OR THE THEME.
THE PROBLEM IS THE DOWNLOAD SOUCE.
WHEN INSTALL THE THEME FROM OCTOBER CMS, IT DOWNLOAD FROM:
https://github.com/vojtasvoboda/oc-newage-theme

ok, now how i can install it from the cms theme page?
if i upload frpm ftp, it not work..



Il giorno dom 24 mar 2019 alle ore 16:21 Beraldo Giuliano <tclone0@gmail.com>
ha scritto:

**Comment by Giulianoberaldo** [comment]
Fixed!
it work
https://worldcapitals.tk/

thanks you

Il giorno dom 24 mar 2019 alle ore 17:18 Beraldo Giuliano <tclone0@gmail.com>
ha scritto:

**Comment by vojtasvoboda** [comment]
How did you fix it?

**Comment by vojtasvoboda** [comment]
@Giulianoberaldo I just released New Age theme version 3.0.0 which contains the latest jQuery, Bootstrap and Font Awesome libraries and should fix all problems mentioned above.
